package com.zoro.legaloa.common;

import java.util.Locale;
import java.util.Map;

/**
 * Keeps API error codes stable while localizing their human-readable message.
 * Clients should branch on the code, never on the translated text.
 */
final class ApiMessageCatalog {
    private static final Map<String, String> ENGLISH = Map.ofEntries(
            Map.entry("VALIDATION_FAILED", "Request validation failed"),
            Map.entry("PARAMETER_INVALID", "The request parameter format is invalid"),
            Map.entry("RESOURCE_CONFLICT", "The resource already exists or its state has changed"),
            Map.entry("INTERNAL_ERROR", "The system could not process the request"),
            Map.entry("PERMISSION_DENIED", "The current account lacks the required permission"),
            Map.entry("MATTER_NOT_FOUND", "The matter does not exist or is not accessible"),
            Map.entry("RESPONSIBLE_USER_INVALID", "The responsible counsel is inactive or outside this organization"),
            Map.entry("OFFICE_INVALID", "The responsible office does not exist or is inactive"),
            Map.entry("OFFICE_ACCESS_DENIED", "You do not have access to the selected office"),
            Map.entry("OFFICE_MANAGE_DENIED", "You cannot manage the selected office"),
            Map.entry("USER_OFFICE_MISMATCH", "The selected user is not assigned to this office"),
            Map.entry("PARTY_INVALID", "The party does not exist or is outside this organization"),
            Map.entry("DOCUMENT_CONTEXT_INVALID", "Select exactly one matter or contract context"),
            Map.entry("DOCUMENT_ACCESS_DENIED", "You do not have access to this document"),
            Map.entry("DOCUMENT_DOWNLOAD_RATE_LIMITED", "Too many downloads in a short period; retry later"),
            Map.entry("DOCUMENT_SECURITY_STATUS_INVALID", "The document security event status is invalid"),
            Map.entry("OFFICE_ACCESS_LEVEL_INVALID", "The office access level is invalid"),
            Map.entry("OFFICE_GRANT_DENIED", "You cannot grant or revoke this office access"),
            Map.entry("OFFICE_PRIMARY_EXPIRY_INVALID", "Primary office access cannot expire"),
            Map.entry("OFFICE_GRANT_EXPIRED", "The access expiry must be in the future"),
            Map.entry("OFFICE_MEMBER_INVALID", "The user is inactive or outside this organization"),
            Map.entry("OFFICE_MEMBERSHIP_NOT_FOUND", "The office membership does not exist"),
            Map.entry("OFFICE_PRIMARY_REVOKE_DENIED", "Assign another primary office before revoking this access"),
            Map.entry("FILE_TYPE_NOT_ALLOWED", "This file type is not allowed"),
            Map.entry("FILENAME_INVALID", "The filename is unsafe, empty, or too long"),
            Map.entry("FILE_EXTENSION_MISMATCH", "The filename extension does not match the declared content type"),
            Map.entry("FILE_SIGNATURE_MISMATCH", "The file signature does not match the declared content type"),
            Map.entry("ARCHIVE_LIMIT_EXCEEDED", "The archive exceeds safe expansion limits"),
            Map.entry("ARCHIVE_PATH_INVALID", "The archive contains an unsafe path"),
            Map.entry("ARCHIVE_EXECUTABLE_NOT_ALLOWED", "Executable archive content is not allowed"),
            Map.entry("MACRO_NOT_ALLOWED", "Macro-enabled Office content is not allowed"),
            Map.entry("FILE_INSPECTION_FAILED", "The uploaded file could not be inspected safely"),
            Map.entry("MALWARE_DETECTED", "The uploaded file failed antivirus scanning"),
            Map.entry("SCANNER_FAILED", "The antivirus service is unavailable; the file remains quarantined"),
            Map.entry("DOCUMENT_NOT_AVAILABLE", "The document is quarantined, rejected, or unavailable"),
            Map.entry("DOCUMENT_VERSION_UNAVAILABLE", "Only safely scanned document versions can be processed"),
            Map.entry("DOCUMENT_INDEX_FAILED", "Document indexing failed; the original file was not changed"),
            Map.entry("DOCUMENT_NOT_FOUND", "The document does not exist or has been deleted"),
            Map.entry("LEGAL_HOLD_RESOURCE_INVALID", "The legal-hold resource is invalid or outside this organization"),
            Map.entry("LEGAL_HOLD_RELEASE_INVALID", "The legal hold does not exist or has already been released"),
            Map.entry("EXPORT_TYPE_INVALID", "This resource type cannot be exported"),
            Map.entry("EXPORT_ACCESS_DENIED", "You do not have access to this export job"),
            Map.entry("EXPORT_NOT_FOUND", "The export job does not exist"),
            Map.entry("UPLOAD_SESSION_INVALID", "The upload session is missing, completed, or expired"),
            Map.entry("UPLOAD_SIZE_MISMATCH", "The uploaded file size does not match the registered size"),
            Map.entry("UPLOAD_HASH_MISMATCH", "The uploaded file integrity check failed"),
            Map.entry("LEAVE_TYPE_INVALID", "The leave type is invalid"),
            Map.entry("LEAVE_TIME_INVALID", "The end time must be later than the start time"),
            Map.entry("LEAVE_TIME_CONFLICT", "An effective leave request already overlaps this period"),
            Map.entry("EXPENSE_MATTER_INVALID", "The related matter is invalid"),
            Map.entry("EXPENSE_SUBMIT_INVALID", "Only the applicant may submit a draft expense claim"),
            Map.entry("MEETING_TIME_INVALID", "The end time must be later than the start time"),
            Map.entry("MEETING_ROOM_INVALID", "The meeting room does not exist or is inactive"),
            Map.entry("MEETING_CAPACITY_EXCEEDED", "The attendee count exceeds the room capacity"),
            Map.entry("MEETING_TIME_CONFLICT", "The room is already booked for the selected period"),
            Map.entry("MEETING_CANCEL_DENIED", "Only the organizer or a room administrator may cancel this booking"),
            Map.entry("ANNOUNCEMENT_TARGET_REQUIRED", "A targeted announcement requires at least one recipient"),
            Map.entry("ANNOUNCEMENT_NOT_DRAFT", "The announcement does not exist or has already been published"),
            Map.entry("ANNOUNCEMENT_NOT_FOUND", "The announcement does not exist or is not accessible"),
            Map.entry("ANNOUNCEMENT_TARGET_INVALID", "One or more announcement recipients are invalid"),
            Map.entry("ARCHIVE_ITEM_INVALID", "The selected document cannot be added to this archive"),
            Map.entry("ARCHIVE_NOT_FOUND", "The archive does not exist or is not accessible"),
            Map.entry("CLIENT_CONTEXT_INVALID", "The client does not exist or is outside this organization"),
            Map.entry("CONTRACT_CONTEXT_INVALID", "The contract does not exist or is not accessible"),
            Map.entry("CONTRACT_DATES_INVALID", "The contract expiry date cannot be earlier than its effective date"),
            Map.entry("CONTRACT_MATTER_INVALID", "One or more related matters are invalid or inaccessible"),
            Map.entry("DEADLINE_CONTEXT_INVALID", "The deadline context is invalid or inaccessible"),
            Map.entry("DINGTALK_AUTH_FAILED", "DingTalk authorization failed"),
            Map.entry("DINGTALK_ID_MISSING", "The DingTalk account does not provide a stable user identifier"),
            Map.entry("DINGTALK_NOT_CONFIGURED", "DingTalk sign-in is not configured"),
            Map.entry("DINGTALK_TOKEN_INVALID", "The DingTalk access token response is invalid"),
            Map.entry("DINGTALK_USER_INVALID", "The DingTalk user response is invalid"),
            Map.entry("DINGTALK_USER_NOT_SYNCED", "This DingTalk user has not been synchronized into the organization"),
            Map.entry("DOCUMENT_VERSION_NOT_FOUND", "The document version does not exist or is not accessible"),
            Map.entry("ENUM_INVALID", "One of the supplied values is not supported"),
            Map.entry("EXPENSE_NOT_FOUND", "The expense claim does not exist or is not accessible"),
            Map.entry("EXPENSE_PAY_INVALID", "Only an approved expense claim can be marked as paid"),
            Map.entry("IDEMPOTENCY_IN_PROGRESS", "An identical request is still being processed"),
            Map.entry("LEAVE_NOT_FOUND", "The leave request does not exist or is not accessible"),
            Map.entry("LEAVE_SUBMIT_INVALID", "Only the applicant may submit a draft leave request"),
            Map.entry("MATTER_CONTEXT_INVALID", "The matter context is invalid or inaccessible"),
            Map.entry("MATTER_ACCESS_DENIED", "You cannot record time against this matter"),
            Map.entry("MATTER_TRANSITION_INVALID", "This matter status transition is not allowed"),
            Map.entry("MATTER_WRITE_DENIED", "You do not have permission to edit this matter"),
            Map.entry("MEETING_BOOKING_NOT_FOUND", "The meeting booking does not exist or is not accessible"),
            Map.entry("NOTIFICATION_NOT_FOUND", "The notification does not exist or is not accessible"),
            Map.entry("OAUTH_STATE_INVALID", "The sign-in state is invalid or has expired"),
            Map.entry("PARTY_NOT_FOUND", "The party does not exist or is not accessible"),
            Map.entry("REJECT_REASON_REQUIRED", "A rejection reason is required"),
            Map.entry("SEAL_CONTEXT_INVALID", "The seal request business context is invalid"),
            Map.entry("SEAL_REQUEST_DENIED", "You do not have permission to operate this seal request"),
            Map.entry("STORAGE_UNAVAILABLE", "Private object storage is unavailable"),
            Map.entry("SYNC_MODE_INVALID", "The directory synchronization mode is invalid"),
            Map.entry("SYNC_PARENT_DEPARTMENT_MISSING", "A parent department is missing from the synchronization snapshot"),
            Map.entry("SYNC_PROVIDER_INVALID", "The directory synchronization provider is not supported"),
            Map.entry("SYNC_USER_DEPARTMENT_MISSING", "A synchronized user references a missing department"),
            Map.entry("TENANT_NOT_CONFIGURED", "The production organization is not configured"),
            Map.entry("TRANSFER_TARGET_INVALID", "The selected transfer recipient is inactive or outside this organization"),
            Map.entry("UPLOAD_OBJECT_NOT_FOUND", "The uploaded object could not be found"),
            Map.entry("USER_NOT_FOUND", "The user does not exist or is not accessible"),
            Map.entry("LAST_ADMIN_PROTECTED", "The last active administrator cannot be disabled or demoted"),
            Map.entry("PAGE_BOUNDS_INVALID", "Page and size must be positive and size cannot exceed 100"),
            Map.entry("SORT_NOT_ALLOWED", "The requested sort field is not allowed"),
            Map.entry("ENGAGEMENT_OFFICE_MISMATCH", "The engagement office must match the matter office"),
            Map.entry("ENGAGEMENT_APPROVAL_INVALID", "The engagement cannot be approved or another engagement is already active"),
            Map.entry("ENGAGEMENT_REQUIRED", "The matter has no approved fee arrangement for this date"),
            Map.entry("ENGAGEMENT_NOT_BILLABLE", "The engagement does not exist or has not been approved"),
            Map.entry("TIME_ENTRY_TRANSITION_INVALID", "The time-entry status does not allow this operation"),
            Map.entry("INVOICE_EMPTY", "There is no approved time or fixed fee to invoice"),
            Map.entry("INVOICE_TRANSITION_INVALID", "The invoice status does not allow this operation"),
            Map.entry("INVOICE_NOT_FOUND", "The invoice does not exist"),
            Map.entry("INVOICE_NOT_PAYABLE", "The invoice cannot receive a payment"),
            Map.entry("PAYMENT_OVER_ALLOCATED", "Payment allocations cannot exceed the received amount"),
            Map.entry("PAYMENT_ALLOCATION_INVALID", "The payment allocation does not match the invoice office, currency, or balance"),
            Map.entry("COLLECTION_TARGET_INVALID", "The invoice or collection owner is invalid"),
            Map.entry("WORK_TASK_OWNER_INVALID", "The task owner is inactive or outside this organization"),
            Map.entry("WORK_TASK_BUSINESS_INVALID", "The related matter is invalid or inaccessible"),
            Map.entry("WORK_TASK_UPDATE_DENIED", "Only the owner or creator may update this task"),
            Map.entry("WORK_TASK_CANCEL_DENIED", "Only the owner or creator may cancel this task"),
            Map.entry("WORK_TASK_NOT_FOUND", "The task does not exist or is not accessible"),
            Map.entry("WORKFLOW_TYPE_INVALID", "This approval business type is not supported"),
            Map.entry("WORKFLOW_ALREADY_RUNNING", "An approval workflow is already running for this business record"),
            Map.entry("WORKFLOW_TASK_DENIED", "The current account cannot operate this approval task"),
            Map.entry("WORKFLOW_BUSINESS_NOT_FOUND", "The approval business record does not exist or is not accessible"),
            Map.entry("WORKFLOW_DECISION_INVALID", "The approval decision is invalid"),
            Map.entry("WORKFLOW_LINK_NOT_FOUND", "The approval workflow link does not exist"),
            Map.entry("WORKFLOW_REMIND_DENIED", "You do not have permission to remind this approval task"),
            Map.entry("WORKFLOW_REMIND_RATE_LIMITED", "A reminder was sent recently; retry after 30 minutes"),
            Map.entry("WORKFLOW_TASK_NOT_FOUND", "The approval task does not exist or has already been completed"),
            Map.entry("TRANSFER_TARGET_SCOPE_DENIED", "The target user cannot access this business scope"),
            Map.entry("IDEMPOTENCY_KEY_REUSED", "The idempotency key was reused with different request data")
    );

    private ApiMessageCatalog() {}

    static String message(String code, String fallback, Locale locale) {
        if (locale != null && "en".equalsIgnoreCase(locale.getLanguage())) {
            return ENGLISH.getOrDefault(code, fallback);
        }
        return fallback;
    }

    static boolean hasEnglishMessage(String code) {
        return ENGLISH.containsKey(code);
    }
}
